rlang fixes

diff --git a/bin/darwin-splash b/bin/darwin-splash
--- a/bin/darwin-splash
+++ b/bin/darwin-splash
@@ -1,16 +1,68 @@
 #!/usr/bin/env bash
-# vim:filetype=bash:
-
-# Copyright (c) Microsoft Corporation.
-# Licensed under the MIT License.
+# vim: noai:ts=4:sw=4:expandtab
+# shellcheck source=/dev/null
+# shellcheck disable=2009
 
 readonly _D="$(dirname "$(readlink -f "$0")")" && cd $_D
 
+cache_uname() {
+    # Cache the output of uname so we don't
+    # have to spawn it multiple times.
+    IFS=" " read -ra uname <<< "$(uname -srm)"
+
+    kernel_name="${uname[0]}"
+    kernel_version="${uname[1]}"
+    kernel_machine="${uname[2]}"
+
+    if [[ "$kernel_name" == "Darwin" ]]; then
+        IFS=$'\n' read -d "" -ra sw_vers <<< "$(awk -F'<|>' '/key|string/ {print $3}' \
+                            "/System/Library/CoreServices/SystemVersion.plist")"
+        for ((i=0;i<${#sw_vers[@]};i+=2)) {
+            case ${sw_vers[i]} in
+                ProductName)          darwin_name=${sw_vers[i+1]} ;;
+                ProductVersion)       osx_version=${sw_vers[i+1]} ;;
+                ProductBuildVersion)  osx_build=${sw_vers[i+1]}   ;;
+            esac
+        }
+    fi
+}
+
+get_os() {
+    # $kernel_name is set in a function called cache_uname and is
+    # just the output of "uname -s".
+    case $kernel_name in
+        Darwin)   os=$darwin_name ;;
+        SunOS)    os=Solaris ;;
+        Haiku)    os=Haiku ;;
+        MINIX)    os=MINIX ;;
+        AIX)      os=AIX ;;
+        IRIX*)    os=IRIX ;;
+        FreeMiNT) os=FreeMiNT ;;
+
+        Linux|GNU*)
+            os=Linux
+        ;;
+
+        *BSD|DragonFly|Bitrig)
+            os=BSD
+        ;;
+
+        CYGWIN*|MSYS*|MINGW*)
+            os=Windows
+        ;;
+
+        *)
+            printf '%s\n' "Unknown OS detected: '$kernel_name', aborting..." >&2
+            printf '%s\n' "Open an issue on GitHub to add support for your OS." >&2
+            exit 1
+        ;;
+    esac
+}
+
+
 trim() {
     local var="$*"
-    # remove leading whitespace characters
     var="${var#"${var%%[![:space:]]*}"}"
-    # remove trailing whitespace characters
     var="${var%"${var##*[![:space:]]}"}"
     printf '%s' "$var"
 }
@@ -36,35 +88,36 @@ ansi_colors()
   r="$esc[0m"
 }
 
-ansi_colors
+main() {
 
-# 32, 33, 36
-# green, yellow, cyan
+    ansi_colors
 
-h3="$reset$bold$purple"
-h2="$reset$bold$yellow"
-h1="$reset$bold$green"
-p1="$reset"
+    h3="$reset$bold$purple"
+    h2="$reset$bold$yellow"
+    h1="$reset$bold$green"
+    p1="$reset"
 
-ip="$(ifconfig -l | xargs -n1 ipconfig getifaddr | paste -sd ' ' -)"
-#ip="$(ip route get 1.1.1.1 | head -1 | cut -d' ' -f7)"
-kernel="$(uname -srm)"
-uptime="$(uptime)"
-hostname="$(hostname)"
-load="$(uptime | cut -f4 -d, | cut -f2 -d:)"
-load="$(trim $load)"
-uptime="$(uptime | cut -f1 -d,)"
-os="$(sw_vers -productVersion)"
-
-# ☉
+    ip="$(ifconfig -l | xargs -n1 ipconfig getifaddr | paste -sd ' ' -)"
+    #ip="$(ip route get 1.1.1.1 | head -1 | cut -d' ' -f7)"
+    kernel="$(uname -srm)"
+    uptime="$(uptime)"
+    hostname="$(hostname)"
+    load="$(uptime | cut -f4 -d, | cut -f2 -d:)"
+    load="$(trim $load)"
+    uptime="$(uptime | cut -f1 -d,)"
+    os="$(sw_vers -productVersion)"
 
 cat <<EOF
 
-${h2} · IP         ${r}${ip}
-${h2} · Kernel     ${r}${kernel}
-${h2} · OS         ${r}MacOS ${os}
-${h2} · Load       ${r}${load}
-${h2} · Uptime     ${r}${uptime}
-${h1} ○ Hostname   ${h3}${hostname}${r}
+    ${h2} · IP         ${r}${ip}
+    ${h2} · Kernel     ${r}${kernel}
+    ${h2} · OS         ${r}MacOS ${os}
+    ${h2} · Load       ${r}${load}
+    ${h2} · Uptime     ${r}${uptime}
+    ${h1} ○ Hostname   ${h3}${hostname}${r}
 
 EOF
+}
+
+main "$@"
+
diff --git a/bin/splash b/bin/splash
--- a/bin/splash
+++ b/bin/splash
@@ -1,8 +1,448 @@
-#!/bin/bash
-# vim:filetype=bash:
+#!/usr/bin/env bash
+# vim: noai:ts=4:sw=4:expandtab
 
-# Copyright (c) Microsoft Corporation.
-# Licensed under the MIT License.
+cache_uname() {
+    # Cache the output of uname so we don't
+    # have to spawn it multiple times.
+    IFS=" " read -ra uname <<< "$(uname -srm)"
+
+    kernel_name="${uname[0]}"
+    kernel_version="${uname[1]}"
+    kernel_machine="${uname[2]}"
+
+    if [[ "$kernel_name" == "Darwin" ]]; then
+        IFS=$'\n' read -d "" -ra sw_vers <<< "$(awk -F'<|>' '/key|string/ {print $3}' \
+                            "/System/Library/CoreServices/SystemVersion.plist")"
+        for ((i=0;i<${#sw_vers[@]};i+=2)) {
+            case ${sw_vers[i]} in
+                ProductName)          darwin_name=${sw_vers[i+1]} ;;
+                ProductVersion)       osx_version=${sw_vers[i+1]} ;;
+                ProductBuildVersion)  osx_build=${sw_vers[i+1]}   ;;
+            esac
+        }
+    fi
+}
+
+get_os() {
+    # $kernel_name is set in a function called cache_uname and is
+    # just the output of "uname -s".
+    case $kernel_name in
+        Darwin)   os=$darwin_name ;;
+        SunOS)    os=Solaris ;;
+
+        Linux|GNU*)
+            os=Linux
+        ;;
+
+        *BSD|DragonFly|Bitrig)
+            os=BSD
+        ;;
+
+        *)
+            printf '%s\n' "Unknown OS detected: '$kernel_name', aborting..." >&2
+            printf '%s\n' "Open an issue on GitHub to add support for your OS." >&2
+            exit 1
+        ;;
+    esac
+}
+
+get_distro() {
+    [[ $distro ]] && return
+
+    case $os in
+        Linux|BSD|MINIX)
+            if [[ -f /bedrock/etc/bedrock-release && $PATH == */bedrock/cross/* ]]; then
+                case $distro_shorthand in
+                    on|tiny) distro="Bedrock Linux" ;;
+                    *) distro=$(< /bedrock/etc/bedrock-release)
+                esac
+
+            elif [[ -f /etc/redstar-release ]]; then
+                case $distro_shorthand in
+                    on|tiny) distro="Red Star OS" ;;
+                    *) distro="Red Star OS $(awk -F'[^0-9*]' '$0=$2' /etc/redstar-release)"
+                esac
+
+            elif [[ -f /etc/siduction-version ]]; then
+                case $distro_shorthand in
+                    on|tiny) distro=Siduction ;;
+                    *) distro="Siduction ($(lsb_release -sic))"
+                esac
+
+            elif [[ -f /etc/mcst_version ]]; then
+                case $distro_shorthand in
+                    on|tiny) distro="OS Elbrus" ;;
+                    *) distro="OS Elbrus $(< /etc/mcst_version)"
+                esac
+
+            elif type -p pveversion >/dev/null; then
+                case $distro_shorthand in
+                    on|tiny) distro="Proxmox VE" ;;
+                    *)
+                        distro=$(pveversion)
+                        distro=${distro#pve-manager/}
+                        distro="Proxmox VE ${distro%/*}"
+                esac
+
+            elif type -p lsb_release >/dev/null; then
+                case $distro_shorthand in
+                    on)   lsb_flags=-si ;;
+                    tiny) lsb_flags=-si ;;
+                    *)    lsb_flags=-sd ;;
+                esac
+                distro=$(lsb_release "$lsb_flags")
+
+            elif [[ -f /etc/os-release || \
+                    -f /usr/lib/os-release || \
+                    -f /etc/openwrt_release || \
+                    -f /etc/lsb-release ]]; then
+
+                # Source the os-release file
+                for file in /etc/lsb-release /usr/lib/os-release \
+                            /etc/os-release  /etc/openwrt_release; do
+                    source "$file" && break
+                done
+
+                # Format the distro name.
+                case $distro_shorthand in
+                    on)   distro="${NAME:-${DISTRIB_ID}} ${VERSION_ID:-${DISTRIB_RELEASE}}" ;;
+                    tiny) distro="${NAME:-${DISTRIB_ID:-${TAILS_PRODUCT_NAME}}}" ;;
+                    off)  distro="${PRETTY_NAME:-${DISTRIB_DESCRIPTION}} ${UBUNTU_CODENAME}" ;;
+                esac
+
+            elif [[ -f /etc/GoboLinuxVersion ]]; then
+                case $distro_shorthand in
+                    on|tiny) distro=GoboLinux ;;
+                    *) distro="GoboLinux $(< /etc/GoboLinuxVersion)"
+                esac
+
+            elif [[ -f /etc/SDE-VERSION ]]; then
+                distro="$(< /etc/SDE-VERSION)"
+                case $distro_shorthand in
+                    on|tiny) distro="${distro% *}" ;;
+                esac
+
+            elif type -p crux >/dev/null; then
+                distro=$(crux)
+                case $distro_shorthand in
+                    on)   distro=${distro//version} ;;
+                    tiny) distro=${distro//version*}
+                esac
+
+            elif type -p tazpkg >/dev/null; then
+                distro="SliTaz $(< /etc/slitaz-release)"
+
+            elif type -p kpt >/dev/null && \
+                 type -p kpm >/dev/null; then
+                distro=KSLinux
+
+            elif [[ -d /system/app/ && -d /system/priv-app ]]; then
+                distro="Android $(getprop ro.build.version.release)"
+
+            # Chrome OS doesn't conform to the /etc/*-release standard.
+            # While the file is a series of variables they can't be sourced
+            # by the shell since the values aren't quoted.
+            elif [[ -f /etc/lsb-release && $(< /etc/lsb-release) == *CHROMEOS* ]]; then
+                distro='Chrome OS'
+
+            elif type -p guix >/dev/null; then
+                case $distro_shorthand in
+                    on|tiny) distro="Guix System" ;;
+                    *) distro="Guix System $(guix -V | awk 'NR==1{printf $4}')"
+                esac
+
+            # Display whether using '-current' or '-release' on OpenBSD.
+            elif [[ $kernel_name = OpenBSD ]] ; then
+                read -ra kernel_info <<< "$(sysctl -n kern.version)"
+                distro=${kernel_info[*]:0:2}
+
+            else
+                for release_file in /etc/*-release; do
+                    distro+=$(< "$release_file")
+                done
+
+                if [[ -z $distro ]]; then
+                    case $distro_shorthand in
+                        on|tiny) distro=$kernel_name ;;
+                        *) distro="$kernel_name $kernel_version" ;;
+                    esac
+
+                    distro=${distro/DragonFly/DragonFlyBSD}
+
+                    # Workarounds for some BSD based distros.
+                    [[ -f /etc/pcbsd-lang ]]       && distro=PCBSD
+                    [[ -f /etc/trueos-lang ]]      && distro=TrueOS
+                    [[ -f /etc/pacbsd-release ]]   && distro=PacBSD
+                    [[ -f /etc/hbsd-update.conf ]] && distro=HardenedBSD
+                fi
+            fi
+
+            if [[ $(< /proc/version) == *Microsoft* || $kernel_version == *Microsoft* ]]; then
+                case $distro_shorthand in
+                    on)   distro+=" [Windows 10]" ;;
+                    tiny) distro="Windows 10" ;;
+                    *)    distro+=" on Windows 10" ;;
+                esac
+
+            elif [[ $(< /proc/version) == *chrome-bot* || -f /dev/cros_ec ]]; then
+                [[ $distro != *Chrome* ]] &&
+                    case $distro_shorthand in
+                        on)   distro+=" [Chrome OS]" ;;
+                        tiny) distro="Chrome OS" ;;
+                        *)    distro+=" on Chrome OS" ;;
+                    esac
+            fi
+
+            distro=$(trim_quotes "$distro")
+            distro=${distro/NAME=}
+
+            # Get Ubuntu flavor.
+            if [[ $distro == "Ubuntu"* ]]; then
+                case $XDG_CONFIG_DIRS in
+                    *"plasma"*)   distro=${distro/Ubuntu/Kubuntu} ;;
+                    *"mate"*)     distro=${distro/Ubuntu/Ubuntu MATE} ;;
+                    *"xubuntu"*)  distro=${distro/Ubuntu/Xubuntu} ;;
+                    *"Lubuntu"*)  distro=${distro/Ubuntu/Lubuntu} ;;
+                    *"budgie"*)   distro=${distro/Ubuntu/Ubuntu Budgie} ;;
+                    *"studio"*)   distro=${distro/Ubuntu/Ubuntu Studio} ;;
+                    *"cinnamon"*) distro=${distro/Ubuntu/Ubuntu Cinnamon} ;;
+                esac
+            fi
+        ;;
+
+        "Mac OS X"|"macOS")
+            case $osx_version in
+                10.4*)  codename="Mac OS X Tiger" ;;
+                10.5*)  codename="Mac OS X Leopard" ;;
+                10.6*)  codename="Mac OS X Snow Leopard" ;;
+                10.7*)  codename="Mac OS X Lion" ;;
+                10.8*)  codename="OS X Mountain Lion" ;;
+                10.9*)  codename="OS X Mavericks" ;;
+                10.10*) codename="OS X Yosemite" ;;
+                10.11*) codename="OS X El Capitan" ;;
+                10.12*) codename="macOS Sierra" ;;
+                10.13*) codename="macOS High Sierra" ;;
+                10.14*) codename="macOS Mojave" ;;
+                10.15*) codename="macOS Catalina" ;;
+                10.16*) codename="macOS Big Sur" ;;
+                11.0*)  codename="macOS Big Sur" ;;
+                *)      codename=macOS ;;
+            esac
+
+            distro="$codename $osx_version $osx_build"
+
+            case $distro_shorthand in
+                on) distro=${distro/ ${osx_build}} ;;
+
+                tiny)
+                    case $osx_version in
+                        10.[4-7]*)            distro=${distro/${codename}/Mac OS X} ;;
+                        10.[8-9]*|10.1[0-1]*) distro=${distro/${codename}/OS X} ;;
+                        10.1[2-6]*|11.0*)     distro=${distro/${codename}/macOS} ;;
+                    esac
+                    distro=${distro/ ${osx_build}}
+                ;;
+            esac
+        ;;
+
+        "iPhone OS")
+            distro="iOS $osx_version"
+
+            # "uname -m" doesn't print architecture on iOS.
+            os_arch=off
+        ;;
+
+        Windows)
+            distro=$(wmic os get Caption)
+            distro=${distro/Caption}
+            distro=${distro/Microsoft }
+        ;;
+
+        Solaris)
+            case $distro_shorthand in
+                on|tiny) distro=$(awk 'NR==1 {print $1,$3}' /etc/release) ;;
+                *)       distro=$(awk 'NR==1 {print $1,$2,$3}' /etc/release) ;;
+            esac
+            distro=${distro/\(*}
+        ;;
+
+        Haiku)
+            distro=Haiku
+        ;;
+
+        AIX)
+            distro="AIX $(oslevel)"
+        ;;
+
+        IRIX)
+            distro="IRIX ${kernel_version}"
+        ;;
+
+        FreeMiNT)
+            distro=FreeMiNT
+        ;;
+    esac
+
+    distro=${distro//Enterprise Server}
+
+    [[ $distro ]] || distro="$os (Unknown)"
+
+    # Get OS architecture.
+    case $os in
+        Solaris|AIX|Haiku|IRIX|FreeMiNT)
+            machine_arch=$(uname -p)
+        ;;
+
+        *)  machine_arch=$kernel_machine ;;
+    esac
+
+    [[ $os_arch == on ]] && \
+        distro+=" $machine_arch"
+
+    [[ ${ascii_distro:-auto} == auto ]] && \
+        ascii_distro=$(trim "$distro")
+}
+
+get_kernel() {
+    # In Windows 'uname' may return the info of GNUenv thus use wmic for OS kernel.
+    [[ $os == Windows ]] && {
+        kernel=$(wmic os get Version)
+        kernel=${kernel/Version}
+        return
+    }
+
+    case $kernel_shorthand in
+        on)  kernel=$kernel_version ;;
+        off) kernel="$kernel_name $kernel_version" ;;
+    esac
+
+    # Hide kernel info if it's identical to the distro info.
+    [[ $os =~ (BSD|MINIX) && $distro == *"$kernel_name"* ]] &&
+        case $distro_shorthand in
+            on|tiny) kernel=$kernel_version ;;
+            *)       unset kernel ;;
+        esac
+}
+
+get_uptime() {
+    # Get uptime in seconds.
+    case $os in
+        Linux|Windows)
+            if [[ -r /proc/uptime ]]; then
+                s=$(< /proc/uptime)
+                s=${s/.*}
+            else
+                boot=$(date -d"$(uptime -s)" +%s)
+                now=$(date +%s)
+                s=$((now - boot))
+            fi
+        ;;
+
+        "Mac OS X"|"macOS"|"iPhone OS"|BSD|FreeMiNT)
+            boot=$(sysctl -n kern.boottime)
+            boot=${boot/\{ sec = }
+            boot=${boot/,*}
+
+            # Get current date in seconds.
+            now=$(date +%s)
+            s=$((now - boot))
+        ;;
+
+    esac
+
+    d="$((s / 60 / 60 / 24)) days"
+    h="$((s / 60 / 60 % 24)) hours"
+    m="$((s / 60 % 60)) mins"
+
+    # Remove plural if < 2.
+    ((${d/ *} == 1)) && d=${d/s}
+    ((${h/ *} == 1)) && h=${h/s}
+    ((${m/ *} == 1)) && m=${m/s}
+
+    # Hide empty fields.
+    ((${d/ *} == 0)) && unset d
+    ((${h/ *} == 0)) && unset h
+    ((${m/ *} == 0)) && unset m
+
+    uptime=${d:+$d, }${h:+$h, }$m
+    uptime=${uptime%', '}
+    uptime=${uptime:-$s secs}
+
+    # Make the output of uptime smaller.
+    case $uptime_shorthand in
+        on) ;;
+
+        tiny)
+            uptime=${uptime/ days/d}
+            uptime=${uptime/ day/d}
+            uptime=${uptime/ hours/h}
+            uptime=${uptime/ hour/h}
+            uptime=${uptime/ mins/m}
+            uptime=${uptime/ min/m}
+            uptime=${uptime/ secs/s}
+            uptime=${uptime//,}
+        ;;
+    esac
+}
+
+
+
+get_model() {
+    case $os in
+        Linux)
+            if [[ -d /system/app/ && -d /system/priv-app ]]; then
+                model="$(getprop ro.product.brand) $(getprop ro.product.model)"
+
+            elif [[ -f /sys/devices/virtual/dmi/id/product_name ||
+                    -f /sys/devices/virtual/dmi/id/product_version ]]; then
+                model=$(< /sys/devices/virtual/dmi/id/product_name)
+                model+=" $(< /sys/devices/virtual/dmi/id/product_version)"
+
+            elif [[ -f /sys/firmware/devicetree/base/model ]]; then
+                model=$(< /sys/firmware/devicetree/base/model)
+
+            elif [[ -f /tmp/sysinfo/model ]]; then
+                model=$(< /tmp/sysinfo/model)
+            fi
+        ;;
+
+        "Mac OS X"|"macOS")
+            model=$(sysctl -n hw.model)
+        ;;
+
+        BSD|MINIX)
+            model=$(sysctl -n hw.vendor hw.product)
+        ;;
+
+        Windows)
+            model=$(wmic computersystem get manufacturer,model)
+            model=${model/Manufacturer}
+            model=${model/Model}
+        ;;
+
+    esac
+
+    # Remove dummy OEM info.
+    model=${model//To be filled by O.E.M.}
+    model=${model//To Be Filled*}
+    model=${model//OEM*}
+    model=${model//Not Applicable}
+    model=${model//System Product Name}
+    model=${model//System Version}
+    model=${model//Undefined}
+    model=${model//Default string}
+    model=${model//Not Specified}
+    model=${model//Type1ProductConfigId}
+    model=${model//INVALID}
+    model=${model//All Series}
+    model=${model//�}
+
+    case $model in
+        "Standard PC"*) model="KVM/QEMU (${model})" ;;
+        OpenBSD*)       model="vmm ($model)" ;;
+    esac
+}
+
 
 readonly _D="$(dirname "$(readlink -f "$0")")" && cd $_D
 
@@ -36,40 +476,41 @@ ansi_colors()
   r="$esc[0m"
 }
 
-ansi_colors
+main() {
+    clear
+    cache_uname
+    get_os
+    get_distro
+    get_kernel
+    get_uptime
+    get_model
 
-# 32, 33, 36
-# green, yellow, cyan
+    echo $os
+    echo $kernel
+    echo $model
 
-h3="$reset$bold$purple"
-h2="$reset$bold$yellow"
-h1="$reset$bold$green"
-p1="$reset"
+    ansi_colors
 
-ip="$(ip route get 1.1.1.1 | head -1 | cut -d' ' -f7)"
-kernel="$(uname -srm)"
-os="$(source /etc/os-release; echo $NAME $VERSION)"
-uptime="$(uptime -p | sed 's/up //')"
-load=$(cat /proc/loadavg | cut -d ' ' -f 1,2,3)
-cpu_t1k=$(cat /sys/class/thermal/thermal_zone0/temp)
-cpu_t=$(printf %.1f "$((10**3 * $cpu_t1k / 1000))e-3")
-temps="$cpu_t° C"
-hostname="$(hostname)"
-model="$(cat /proc/cpuinfo | grep -i model | head -2 | cut -f2 -d: | tail -1)"
-model="$(trim $model)"
-uptime="$(uptime --pretty)"
+    h3="$reset$bold$purple"
+    h2="$reset$bold$yellow"
+    h1="$reset$bold$green"
+    p1="$reset"
 
-# ☉
+    ip="$(ifconfig -l | xargs -n1 ipconfig getifaddr | paste -sd ' ' -)"
+    #ip="$(ip route get 1.1.1.1 | head -1 | cut -d' ' -f7)"
+    hostname="$(hostname)"
 
 cat <<EOF
 
-${h2} · Hostname   ${h2}${hostname}
-${h2} · IP         ${r}${ip}
-${h2} · Kernel     ${r}${kernel}
-${h2} · OS         ${r}${os}
-${h2} · Load       ${r}${load}
-${h2} · CPU        ${r}${temps}
-${h2} · Uptime     ${r}${uptime}
-${h1} ○ Model      ${h3}${model}${r}
+    ${h2} · IP         ${r}${ip}
+    ${h2} · Kernel     ${r}${kernel}
+    ${h2} · OS         ${r}${os}
+    ${h2} · Load       ${r}${load}
+    ${h2} · Uptime     ${r}${uptime}
+    ${h1} ○ Hostname   ${h3}${hostname}${r}
 
 EOF
+}
+
+main "$@"
+
